spring:
  datasource:
    url: "jdbc:h2:mem:test"
    username: "admin"
    password: "123456"
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
logging:
  level:
    com:
      baomidou:
        mybatisplus: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


